apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: browser
  namespace: buildbarn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      containers:
      - image: buildbarn/bb-browser:20190303T064412Z-dd7ac26
        name: browser
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          name: config-storage-clients
        name: config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: browser
  namespace: buildbarn
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: browser
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: browser
  namespace: buildbarn
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: browser
          servicePort: 80
